/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BNavText: typeof import('bootstrap-vue-next')['BNavText']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    EvaluateScoreBar: typeof import('./src/components/EvaluateScoreBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconHungarofit: typeof import('./src/components/icons/IconHungarofit.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
